"use client";

import { useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import {
  api,
  type DocumentClassification,
  type DocumentQualityCheck,
  type DocumentRecord,
  type DocumentTypeDefinition,
  type Fact,
  type FactSource,
  type FactStatus,
  type Person,
  type PersonRole,
  type Requirement,
  type RequirementDocumentMatch,
  type RequirementCompletenessEvaluation,
  type RequirementLevel,
  type TaskRecord,
  type TaskStatus,
} from "@/lib/api";
import { StatusBadge } from "./StatusBadge";

const PERSON_ROLES: PersonRole[] = ["applicant", "sponsor", "host", "representative", "other"];
const FACT_SOURCES: FactSource[] = ["google_form", "whatsapp", "document", "manual", "derived"];
const FACT_STATUSES: FactStatus[] = ["confirmed", "proposed", "conflict", "rejected"];
const REQUIREMENT_LEVELS: RequirementLevel[] = ["required", "conditional", "supporting", "optional"];
const TASK_STATUSES: TaskStatus[] = ["open", "in_progress", "completed", "cancelled"];
const classificationReviewer = process.env.NEXT_PUBLIC_WORKFLOW_ACTOR ?? "manual-ui";

function Failure({ children }: { children: ReactNode }) { return <div className="form-error field-full" role="alert">{children}</div>; }
function Empty({ children }: { children: ReactNode }) { return <div className="empty-state">{children}</div>; }
function optional(value: FormDataEntryValue | null) { const text = String(value ?? "").trim(); return text || null; }
function displayJson(value: unknown) { return typeof value === "string" ? value : JSON.stringify(value); }
function parseJson(value: string): unknown { try { return JSON.parse(value); } catch { return value; } }

type SectionProps<T> = { caseId: string; items: T[]; onChanged: () => Promise<void> };

export function PeopleSection({ caseId, items, onChanged }: SectionProps<Person>) {
  const [editing, setEditing] = useState<Person | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const data = new FormData(event.currentTarget);
    const payload = { first_name: String(data.get("first_name")), last_name: String(data.get("last_name")), roles: data.getAll("roles") as PersonRole[] };
    try { editing ? await api.updatePerson(editing.id, payload) : await api.createPerson(caseId, payload); setOpen(false); setEditing(null); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Person could not be saved."); }
  }
  return <section className="section-card" id="people"><div className="section-heading"><h2>People</h2><button className="button button-small" onClick={() => { setEditing(null); setOpen(!open); }}>Add person</button></div>
    {!items.length ? <Empty>No people recorded.</Empty> : <div className="record-list">{items.map(person => <div className="record" key={person.id}><div className="record-head"><div><h3>{person.first_name} {person.last_name}</h3><div className="record-meta">{person.roles.map(role => <StatusBadge value={role} key={role} />)}</div></div><button className="button button-secondary button-small" onClick={() => { setEditing(person); setOpen(true); }}>Edit</button></div></div>)}</div>}
    {open && <form className="form-grid" onSubmit={submit} key={editing?.id ?? "new"}><div className="field"><label htmlFor="person-first-name">First name</label><input id="person-first-name" name="first_name" defaultValue={editing?.first_name} required /></div><div className="field"><label htmlFor="person-last-name">Last name</label><input id="person-last-name" name="last_name" defaultValue={editing?.last_name} required /></div><fieldset className="field field-full"><legend>Roles</legend><div className="checkboxes">{PERSON_ROLES.map(role => <label key={role}><input type="checkbox" name="roles" value={role} defaultChecked={editing?.roles.includes(role) ?? role === "applicant"} />{role}</label>)}</div></fieldset>{error && <Failure>{error}</Failure>}<div className="button-row field-full"><button className="button">Save person</button><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button></div></form>}
  </section>;
}

export function FactsSection({ caseId, items, people, onChanged }: SectionProps<Fact> & { people: Person[] }) {
  const [editing, setEditing] = useState<Fact | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const confidence = optional(data.get("confidence"));
    const payload = { person_id: optional(data.get("person_id")), key: String(data.get("key")), value_json: parseJson(String(data.get("value_json"))), source_type: String(data.get("source_type")) as FactSource, source_reference: String(data.get("source_reference")), confidence: confidence === null ? null : Number(confidence), status: String(data.get("status")) as FactStatus };
    try { editing ? await api.updateFact(editing.id, payload) : await api.createFact(caseId, payload); setOpen(false); setEditing(null); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Fact could not be saved."); }
  }
  return <section className="section-card" id="facts"><div className="section-heading"><h2>Facts</h2><button className="button button-small" onClick={() => { setEditing(null); setOpen(!open); }}>Add fact</button></div>
    {!items.length ? <Empty>No facts recorded.</Empty> : <div className="record-list">{items.map(fact => <div className={`record ${fact.status === "conflict" ? "record-conflict" : ""}`} key={fact.id}><div className="record-head"><div><h3>{fact.key}</h3><div className="record-meta"><StatusBadge value={fact.status} /><StatusBadge value={fact.source_type} />{fact.confidence !== null && <span className="badge">{Math.round(fact.confidence * 100)}% confidence</span>}</div></div><button className="button button-secondary button-small" onClick={() => { setEditing(fact); setOpen(true); }}>Edit</button></div><div className="json-value">{displayJson(fact.value_json)}</div><p className="muted">Source: {fact.source_reference}</p></div>)}</div>}
    {open && <form className="form-grid" onSubmit={submit} key={editing?.id ?? "new"}><div className="field"><label>Key</label><input name="key" required defaultValue={editing?.key} /></div><div className="field"><label>Person</label><select name="person_id" defaultValue={editing?.person_id ?? ""}><option value="">Case-level fact</option>{people.map(p => <option value={p.id} key={p.id}>{p.first_name} {p.last_name}</option>)}</select></div><div className="field field-full"><label>Value (plain text or JSON)</label><textarea name="value_json" required defaultValue={editing ? displayJson(editing.value_json) : ""} /></div><div className="field"><label>Source</label><select name="source_type" defaultValue={editing?.source_type ?? "manual"}>{FACT_SOURCES.map(value => <option key={value}>{value}</option>)}</select></div><div className="field"><label>Source reference</label><input name="source_reference" required defaultValue={editing?.source_reference ?? "Employee entry"} /></div><div className="field"><label>Status</label><select name="status" defaultValue={editing?.status ?? "confirmed"}>{FACT_STATUSES.map(value => <option key={value}>{value}</option>)}</select></div><div className="field"><label>Confidence (0–1)</label><input type="number" name="confidence" min="0" max="1" step="0.01" defaultValue={editing?.confidence ?? ""} /></div>{error && <Failure>{error}</Failure>}<div className="button-row field-full"><button className="button">Save fact</button><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button></div></form>}
  </section>;
}

export function RequirementsSection({ caseId, items, people, documents, matches, completenessEvaluations = [], onChanged }: SectionProps<Requirement> & { people: Person[]; documents: DocumentRecord[]; matches: RequirementDocumentMatch[]; completenessEvaluations?: RequirementCompletenessEvaluation[] }) {
  const [editing, setEditing] = useState<Requirement | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [evaluationMessage, setEvaluationMessage] = useState(""); const [evaluating, setEvaluating] = useState(false);
  async function evaluate() {
    setError(""); setEvaluationMessage(""); setEvaluating(true);
    try { const result = await api.evaluateRequirements(caseId); setEvaluationMessage(`${result.created.length} created, ${result.reactivated.length} reactivated, ${result.deactivated.length} deactivated.`); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Requirements could not be evaluated."); }
    finally { setEvaluating(false); }
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const fulfillment = String(data.get("fulfillment_status"));
    const base = { document_type: String(data.get("document_type")), owner_role: String(data.get("owner_role")) as PersonRole, owner_person_id: optional(data.get("owner_person_id")), requirement_level: String(data.get("requirement_level")) as RequirementLevel, rule_id: editing?.rule_id ?? null, reason: String(data.get("reason")), is_blocking: data.get("is_blocking") === "on", active: data.get("active") === "on" };
    try { if (editing) await api.updateRequirement(editing.id, { ...base, fulfillment_status: fulfillment as Requirement["fulfillment_status"], waiver_reason: fulfillment === "waived" ? optional(data.get("waiver_reason")) : null, waived_by: fulfillment === "waived" ? optional(data.get("waived_by")) : null }); else await api.createRequirement(caseId, base); setOpen(false); setEditing(null); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Requirement could not be saved."); }
  }
  return <section className="section-card" id="requirements"><div className="section-heading"><h2>Requirements</h2><div className="button-row"><button className="button button-secondary button-small" disabled={evaluating} onClick={() => void evaluate()}>{evaluating ? "Evaluating…" : "Re-evaluate rules"}</button><button className="button button-small" onClick={() => { setEditing(null); setOpen(!open); }}>Add requirement</button></div></div>
    <RequirementCompletenessPanels requirements={items} documents={documents} matches={matches} evaluations={completenessEvaluations} onChanged={onChanged} />
    {evaluationMessage && <div className="success-message" role="status">{evaluationMessage}</div>}{error && <Failure>{error}</Failure>}
    {!items.length ? <Empty>No requirements recorded.</Empty> : <div className="record-list">{items.map(item => { const matched = matches.filter(match => match.requirement_id === item.id).map(match => documents.find(document => document.id === match.document_id)).filter((document): document is DocumentRecord => Boolean(document)); return <div className="record" key={item.id}><div className="record-head"><div><h3>{item.document_type}</h3><p>{item.reason}</p><div className="record-meta"><StatusBadge value={item.fulfillment_status} /><StatusBadge value={item.requirement_level} />{item.is_blocking && <StatusBadge value="blocking" />}{!item.active && <StatusBadge value="inactive" />}<span className="badge">{item.owner_role}</span><span className={`badge ${item.rule_id ? "badge-automatic" : ""}`}>{item.rule_id ? "Automatic" : "Manual"}</span></div><p className="muted">Owner: {people.find(person => person.id === item.owner_person_id) ? `${people.find(person => person.id === item.owner_person_id)!.first_name} ${people.find(person => person.id === item.owner_person_id)!.last_name}` : item.owner_role}{item.rule_id ? ` · Rule: ${item.rule_id}` : ""}</p>{item.waiver_reason && <p className="muted">Waived by {item.waived_by}: {item.waiver_reason}</p>}<div className="match-summary"><strong>Matched documents</strong>{matched.length ? <ul>{matched.map(document => <li key={document.id}><a href={api.documentContentUrl(document.id)} target="_blank" rel="noreferrer">{document.original_filename}</a></li>)}</ul> : <span className="muted">None</span>}<small>Matched only — not quality-approved.</small></div></div><button className="button button-secondary button-small" onClick={() => { setEditing(item); setOpen(true); }}>Edit</button></div></div>; })}</div>}
    {open && <form className="form-grid" onSubmit={submit} key={editing?.id ?? "new"}><div className="field"><label>Document type</label><input name="document_type" required defaultValue={editing?.document_type} /></div><div className="field"><label>Requirement level</label><select name="requirement_level" defaultValue={editing?.requirement_level ?? "required"}>{REQUIREMENT_LEVELS.map(value => <option key={value}>{value}</option>)}</select></div><div className="field"><label>Owner role</label><select name="owner_role" defaultValue={editing?.owner_role ?? "applicant"}>{PERSON_ROLES.map(value => <option key={value}>{value}</option>)}</select></div><div className="field"><label>Owner person</label><select name="owner_person_id" defaultValue={editing?.owner_person_id ?? ""}><option value="">Not assigned</option>{people.map(p => <option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></div><div className="field field-full"><label>Reason</label><textarea name="reason" required defaultValue={editing?.reason} /></div>{editing?.rule_id && <div className="field"><label>Generated by rule</label><input value={editing.rule_id} readOnly /></div>}{editing && <><div className="field"><label>Fulfillment</label><select name="fulfillment_status" defaultValue={editing.fulfillment_status}><option>pending</option><option>fulfilled</option><option>waived</option></select></div><div className="field"><label>Waiver reason (when waived)</label><input name="waiver_reason" defaultValue={editing.waiver_reason ?? ""} /></div><div className="field"><label>Waived by (when waived)</label><input name="waived_by" defaultValue={editing.waived_by ?? ""} /></div></>}<fieldset className="field field-full"><div className="checkboxes"><label><input name="is_blocking" type="checkbox" defaultChecked={editing?.is_blocking ?? true} />Blocking</label><label><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} />Active</label></div></fieldset>{error && <Failure>{error}</Failure>}<div className="button-row field-full"><button className="button">Save requirement</button><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button></div></form>}
  </section>;
}

export function DocumentsSection({ caseId, items, people, requirements, documentTypes, matches, classifications = [], qualityChecks = [], onChanged }: SectionProps<DocumentRecord> & { people: Person[]; requirements: Requirement[]; documentTypes: DocumentTypeDefinition[]; matches: RequirementDocumentMatch[]; classifications?: DocumentClassification[]; qualityChecks?: DocumentQualityCheck[] }) {
  const [editing, setEditing] = useState<DocumentRecord | null>(null); const [uploadOpen, setUploadOpen] = useState(false); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [managing, setManaging] = useState<string | null>(null); const [candidates, setCandidates] = useState<Requirement[]>([]); const [classifying, setClassifying] = useState<string | null>(null); const [correcting, setCorrecting] = useState<DocumentClassification | null>(null);
  async function submitUpload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setMessage(""); if (!selectedFile) { setError("Select a PDF, JPEG or PNG file."); return; } const data = new FormData(event.currentTarget); setUploading(true);
    try { await api.uploadDocument(caseId, selectedFile, optional(data.get("document_type")) ?? undefined, optional(data.get("person_id")) ?? undefined); setMessage(`${selectedFile.name} uploaded.`); setSelectedFile(null); setUploadOpen(false); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Document could not be uploaded."); }
    finally { setUploading(false); }
  }
  async function submitMetadata(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing) return; setError(""); const data = new FormData(event.currentTarget);
    try { await api.updateDocument(editing.id, { document_type: optional(data.get("document_type")), person_id: optional(data.get("person_id")) }); setEditing(null); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Document assignment could not be saved."); }
  }
  async function manage(document: DocumentRecord) { setError(""); setManaging(document.id); try { setCandidates(await api.matchingRequirements(document.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Compatible requirements could not be loaded."); } }
  async function match(requirementId: string, documentId: string) { setError(""); try { await api.matchDocument(requirementId, documentId, "manual-ui"); await onChanged(); setCandidates(await api.matchingRequirements(documentId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Document could not be matched."); } }
  async function unmatch(requirementId: string, documentId: string) { setError(""); try { await api.unmatchDocument(requirementId, documentId); await onChanged(); setCandidates(await api.matchingRequirements(documentId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Document match could not be removed."); } }
  async function classify(documentId: string) { setError(""); setMessage(""); setClassifying(documentId); try { const result = await api.classifyDocument(documentId); setMessage(result.status === "failed" ? "Classification unavailable. Assign manually or try again." : "Automatic suggestion is ready for employee review."); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Classification could not be started."); } finally { setClassifying(null); } }
  async function accept(item: DocumentClassification) { setError(""); try { await api.acceptClassification(item.document_id, item.id, classificationReviewer); setMessage("Suggestion accepted and document metadata updated."); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Suggestion could not be accepted."); } }
  async function reject(item: DocumentClassification) { setError(""); try { await api.rejectClassification(item.document_id, item.id, classificationReviewer); setMessage("Suggestion rejected. Document metadata was not changed."); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Suggestion could not be rejected."); } }
  async function correct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!correcting) return; setError(""); const data = new FormData(event.currentTarget); try { await api.correctClassification(correcting.document_id, correcting.id, { reviewed_by: classificationReviewer, document_type: String(data.get("document_type")), person_id: String(data.get("person_id")) }); setCorrecting(null); setMessage("Correction saved as authoritative metadata."); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Correction could not be saved."); } }
  function selected(event: ChangeEvent<HTMLInputElement>) { setSelectedFile(event.target.files?.[0] ?? null); setMessage(""); setError(""); }
  return <section className="section-card" id="documents"><div className="section-heading"><div><h2>Documents</h2><span className="muted">Upload, assign and manually match received files.</span></div><button className="button button-small" onClick={() => setUploadOpen(!uploadOpen)}>Upload document</button></div>
    <DocumentQualityPanels documents={items} checks={qualityChecks} onChanged={onChanged} />
    {message && <div className="success-message" role="status">{message}</div>}{error && <Failure>{error}</Failure>}
    {uploadOpen && <form className="form-grid" onSubmit={submitUpload}><div className="field field-full"><label htmlFor="document-file">File</label><input id="document-file" name="file" type="file" accept="application/pdf,image/jpeg,image/png" onChange={selected} /><span className="muted">{selectedFile ? `Selected: ${selectedFile.name}` : "PDF, JPEG or PNG."}</span></div><div className="field"><label>Document type (optional)</label><select aria-label="Document type (optional)" name="document_type"><option value="">Needs assignment</option>{documentTypes.map(type => <option key={type.id} value={type.id}>{type.label}</option>)}</select></div><div className="field"><label>Person (optional)</label><select aria-label="Person (optional)" name="person_id"><option value="">Needs assignment</option>{people.map(person => <option key={person.id} value={person.id}>{person.first_name} {person.last_name}</option>)}</select></div><div className="button-row field-full"><button className="button" disabled={uploading}>{uploading ? "Uploading…" : "Upload"}</button><button type="button" className="button button-secondary" onClick={() => setUploadOpen(false)}>Cancel</button></div></form>}
    {!items.length ? <Empty>No documents uploaded.</Empty> : <div className="record-list">{items.map(item => { const documentMatches = matches.filter(matchItem => matchItem.document_id === item.id); const owner = people.find(person => person.id === item.person_id); return <div className={`record ${!item.document_type || !item.person_id ? "record-needs-assignment" : ""}`} key={item.id}><div className="record-head"><div><h3>{item.original_filename}</h3><p>{documentTypes.find(type => type.id === item.document_type)?.label ?? "Document type needs assignment"}</p><div className="record-meta">{(!item.document_type || !item.person_id) && <span className="badge badge-pending">Needs assignment</span>}<span className="badge">{item.source_type}</span><span className="badge">{item.mime_type}</span></div><p className="muted">Owner: {owner ? `${owner.first_name} ${owner.last_name}` : "Needs assignment"}</p><div className="match-summary"><strong>Matched requirements</strong>{documentMatches.length ? <ul>{documentMatches.map(matchItem => <li key={matchItem.id}>{requirements.find(requirement => requirement.id === matchItem.requirement_id)?.document_type ?? "Historical requirement"}</li>)}</ul> : <span className="muted">None</span>}</div></div><div className="button-row"><a className="button button-secondary button-small" href={api.documentContentUrl(item.id)} target="_blank" rel="noreferrer">Open / Download</a><button className="button button-secondary button-small" onClick={() => setEditing(item)}>Change metadata</button><button className="button button-small" onClick={() => void manage(item)}>Manage matches</button></div></div>{managing === item.id && <div className="match-manager"><h4>Manual requirement matches</h4>{documentMatches.map(matchItem => { const requirement = requirements.find(value => value.id === matchItem.requirement_id); return <div className="match-row" key={matchItem.id}><span>{requirement?.document_type ?? "Historical requirement"}{requirement && !requirement.active ? " (inactive)" : ""}</span><button className="button button-danger button-small" onClick={() => void unmatch(matchItem.requirement_id, item.id)}>Unmatch</button></div>; })}<h4>Compatible active requirements</h4>{candidates.filter(candidate => !documentMatches.some(matchItem => matchItem.requirement_id === candidate.id)).length ? candidates.filter(candidate => !documentMatches.some(matchItem => matchItem.requirement_id === candidate.id)).map(candidate => <div className="match-row" key={candidate.id}><span>{candidate.document_type} — {candidate.owner_role}</span><button className="button button-small" onClick={() => void match(candidate.id, item.id)}>Match</button></div>) : <p className="muted">No additional compatible requirements. Assign both type and person first if needed.</p>}<button className="button button-secondary button-small" onClick={() => setManaging(null)}>Close</button></div>}</div>; })}</div>}
    {!!items.length && <div className="classification-list"><h3>Automatic classification</h3><p className="muted">Suggestions are not authoritative until an employee accepts or corrects them.</p>{items.map(document => { const history = classifications.filter(item => item.document_id === document.id); const latest = history[0]; const current = latest?.status === "suggested" ? latest : undefined; return <div className="classification-panel" key={`classification-${document.id}`}><div className="record-head"><div><strong>{document.original_filename}</strong><div className="record-meta"><StatusBadge value={document.classification_status} /></div></div><button className="button button-secondary button-small" disabled={classifying === document.id} onClick={() => void classify(document.id)}>{classifying === document.id ? "Classifying…" : history.length ? "Try again" : "Classify document"}</button></div>{current && <div className="suggestion-card"><p className="eyebrow">Automatic suggestion</p><p><strong>Type:</strong> {documentTypes.find(type => type.id === current.suggested_document_type)?.label ?? "No type suggestion"}</p><p><strong>Owner:</strong> {people.find(person => person.id === current.suggested_person_id) ? `${people.find(person => person.id === current.suggested_person_id)?.first_name} ${people.find(person => person.id === current.suggested_person_id)?.last_name}` : "No unambiguous owner suggestion"}</p><p><strong>Confidence:</strong> {current.confidence === null ? "Not available" : `${Math.round(current.confidence * 100)}%`}</p><strong>Evidence</strong><ul>{current.evidence_json.map((evidence, index) => <li key={`${evidence.type}-${index}`}>{evidence.value}</li>)}</ul><div className="button-row"><button className="button button-small" onClick={() => void accept(current)}>Accept suggestion</button><button className="button button-secondary button-small" onClick={() => setCorrecting(current)}>Correct suggestion</button><button className="button button-danger button-small" onClick={() => void reject(current)}>Reject suggestion</button></div></div>}{latest?.status === "failed" && <div className="form-error">Classification unavailable. Use Change metadata for manual assignment or try again.</div>}{history.length > 0 && <details><summary>Classification history ({history.length})</summary><ul className="classification-history">{history.map(item => <li key={item.id}><strong>{new Date(item.created_at).toLocaleString()}</strong> — {item.status}; suggested {documentTypes.find(type => type.id === item.suggested_document_type)?.label ?? "no type"}{item.corrected_document_type ? `; corrected to ${documentTypes.find(type => type.id === item.corrected_document_type)?.label ?? item.corrected_document_type}` : ""}{item.reviewed_by ? ` by ${item.reviewed_by}` : ""}</li>)}</ul></details>}</div>; })}</div>}
    {correcting && <form className="form-grid" onSubmit={correct} key={`correction-${correcting.id}`}><h3 className="field-full">Correct automatic suggestion</h3><div className="field"><label>Correct document type</label><select aria-label="Correct document type" name="document_type" defaultValue={correcting.suggested_document_type ?? ""} required><option value="" disabled>Select a catalog type</option>{documentTypes.map(type => <option key={type.id} value={type.id}>{type.label}</option>)}</select></div><div className="field"><label>Correct person</label><select aria-label="Correct person" name="person_id" defaultValue={correcting.suggested_person_id ?? ""} required><option value="" disabled>Select an existing person</option>{people.map(person => <option key={person.id} value={person.id}>{person.first_name} {person.last_name}</option>)}</select></div><p className="muted field-full">The original suggestion remains in classification history. Existing incompatible matches must be removed first.</p><div className="button-row field-full"><button className="button">Save correction</button><button type="button" className="button button-secondary" onClick={() => setCorrecting(null)}>Cancel</button></div></form>}
    {editing && <form className="form-grid" onSubmit={submitMetadata} key={editing.id}><div className="field"><label>Document type</label><select name="document_type" defaultValue={editing.document_type ?? ""}><option value="">Needs assignment</option>{documentTypes.map(type => <option key={type.id} value={type.id}>{type.label}</option>)}</select></div><div className="field"><label>Person</label><select name="person_id" defaultValue={editing.person_id ?? ""}><option value="">Needs assignment</option>{people.map(person => <option key={person.id} value={person.id}>{person.first_name} {person.last_name}</option>)}</select></div><p className="muted field-full">Existing matches must be removed before an incompatible assignment can be saved.</p><div className="button-row field-full"><button className="button">Save assignment</button><button type="button" className="button button-secondary" onClick={() => setEditing(null)}>Cancel</button></div></form>}
  </section>;
}

function DocumentQualityPanels({ documents, checks, onChanged }: { documents: DocumentRecord[]; checks: DocumentQualityCheck[]; onChanged: () => Promise<void> }) {
  const [busy, setBusy] = useState<string | null>(null);
  const [reviewing, setReviewing] = useState<{ check: DocumentQualityCheck; decision: "accept" | "reject" } | null>(null);
  const [error, setError] = useState("");

  async function run(documentId: string) {
    setBusy(documentId); setError("");
    try { await api.runQualityCheck(documentId); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Quality analysis could not be completed."); }
    finally { setBusy(null); }
  }
  async function review(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!reviewing) return; setError("");
    const reason = String(new FormData(event.currentTarget).get("reason") ?? "").trim();
    try {
      if (reviewing.decision === "accept") await api.acceptQuality(reviewing.check.document_id, reviewing.check.id, classificationReviewer, reason);
      else await api.rejectQuality(reviewing.check.document_id, reviewing.check.id, classificationReviewer, reason);
      setReviewing(null); await onChanged();
    } catch (value) { setError(value instanceof Error ? value.message : "Manual review could not be saved."); }
  }

  if (!documents.length) return null;
  return <div className="classification-list" aria-label="Document quality">
    <h3>Document quality</h3>
    <p className="muted">Quality is separate from classification and matching. Manual decisions require a reason.</p>
    {error && <Failure>{error}</Failure>}
    {documents.map(document => {
      const history = checks.filter(check => check.document_id === document.id);
      const latest = history[0];
      return <div className="classification-panel" key={`quality-${document.id}`}>
        <div className="record-head"><div><strong>{document.original_filename}</strong><div className="record-meta"><StatusBadge value={document.quality_status} /></div></div>
          <button className="button button-secondary button-small" disabled={busy === document.id} onClick={() => void run(document.id)}>{busy === document.id ? "Checking…" : history.length ? "Run quality check again" : "Run quality check"}</button>
        </div>
        {latest && <><ul>{latest.checks_json.map(item => <li key={item.check_id}><strong>{item.status === "pass" ? "✓" : item.status === "fail" ? "✗" : "?"} {item.check_id}</strong>{item.evidence ? ` — ${item.evidence}` : ""}{item.issue ? ` — ${item.issue}` : ""}</li>)}</ul>
          {latest.issues_json.length > 0 && <p className="form-error">{latest.issues_json.map(item => item.message).join("; ")}</p>}
          {!latest.review_decision && <div className="button-row"><button className="button button-small" onClick={() => setReviewing({ check: latest, decision: "accept" })}>Accept document manually</button><button className="button button-danger button-small" onClick={() => setReviewing({ check: latest, decision: "reject" })}>Reject document manually</button></div>}
          <details><summary>Quality history ({history.length})</summary><ul>{history.map(item => <li key={item.id}>{new Date(item.created_at).toLocaleString()} — {item.status}{item.review_decision ? `; ${item.review_decision} by ${item.reviewed_by}: ${item.review_reason}` : ""}</li>)}</ul></details></>}
      </div>;
    })}
    {reviewing && <form className="form-grid" onSubmit={review}><h3 className="field-full">{reviewing.decision === "accept" ? "Accept document manually" : "Reject document manually"}</h3><div className="field field-full"><label htmlFor="quality-review-reason">Reason</label><textarea id="quality-review-reason" name="reason" minLength={3} required /></div><div className="button-row field-full"><button className={reviewing.decision === "accept" ? "button" : "button button-danger"}>{reviewing.decision === "accept" ? "Accept document manually" : "Reject document manually"}</button><button type="button" className="button button-secondary" onClick={() => setReviewing(null)}>Cancel</button></div></form>}
  </div>;
}

function RequirementCompletenessPanels({ requirements, documents, matches, evaluations, onChanged }: { requirements: Requirement[]; documents: DocumentRecord[]; matches: RequirementDocumentMatch[]; evaluations: RequirementCompletenessEvaluation[]; onChanged: () => Promise<void> }) {
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState("");
  async function evaluate(requirementId: string) {
    setBusy(requirementId); setError("");
    try { await api.evaluateCompleteness(requirementId); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Completeness could not be evaluated."); }
    finally { setBusy(null); }
  }
  if (!requirements.length) return null;
  return <div className="classification-list" aria-label="Requirement completeness"><h3>Requirement completeness</h3><p className="muted">Matched files and accepted evidence are shown separately; only passed or manually accepted evidence can fulfil a requirement.</p>{error && <Failure>{error}</Failure>}
    {requirements.map(requirement => {
      const matched = matches.filter(item => item.requirement_id === requirement.id).map(item => documents.find(document => document.id === item.document_id)).filter((document): document is DocumentRecord => Boolean(document));
      const accepted = matched.filter(document => document.quality_status === "passed" || document.quality_status === "manual_accepted");
      const history = evaluations.filter(item => item.requirement_id === requirement.id); const latest = history[0];
      return <div className="classification-panel" key={`completeness-${requirement.id}`}><div className="record-head"><div><strong>{requirement.document_type}</strong><div className="record-meta"><StatusBadge value={requirement.fulfillment_status} />{latest && <StatusBadge value={latest.status} />}</div></div><button className="button button-secondary button-small" disabled={busy === requirement.id} onClick={() => void evaluate(requirement.id)}>{busy === requirement.id ? "Evaluating…" : "Evaluate completeness"}</button></div>
        <p><strong>Matched documents:</strong> {matched.length}</p><p><strong>Accepted documents:</strong> {accepted.length}</p><p><strong>Requirement status:</strong> {requirement.fulfillment_status}{requirement.fulfillment_source ? ` (${requirement.fulfillment_source})` : ""}</p>
        {latest && <><p>{latest.explanation}</p>{latest.missing_json.length > 0 && <p><strong>Missing:</strong> {latest.missing_json.join(", ")}</p>}{Array.isArray(latest.coverage_json.covered_months) && <p><strong>Coverage:</strong> {(latest.coverage_json.covered_months as string[]).join(", ") || "None"}</p>}<details><summary>Completeness history ({history.length})</summary><ul>{history.map(item => <li key={item.id}>{new Date(item.created_at).toLocaleString()} — {item.status}; {item.accepted_count} accepted of {item.matched_count} matched</li>)}</ul></details></>}
      </div>;
    })}
  </div>;
}

export function TasksSection({ caseId, items, requirements, documents, onChanged }: SectionProps<TaskRecord> & { requirements: Requirement[]; documents: DocumentRecord[] }) {
  const [editing, setEditing] = useState<TaskRecord | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function saveStatus(item: TaskRecord, status: TaskStatus) { setError(""); try { await api.updateTask(item.id, { status, completed_at: status === "completed" ? new Date().toISOString() : null }); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Task could not be updated."); } }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const status = String(data.get("status")) as TaskStatus;
    const payload = { type: String(data.get("type")), title: String(data.get("title")), description: String(data.get("description")), status, priority: String(data.get("priority")), blocking: data.get("blocking") === "on", related_requirement_id: optional(data.get("related_requirement_id")), related_document_id: optional(data.get("related_document_id")), completed_at: status === "completed" ? (editing?.completed_at ?? new Date().toISOString()) : null };
    try { editing ? await api.updateTask(editing.id, payload) : await api.createTask(caseId, payload); setOpen(false); setEditing(null); await onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Task could not be saved."); }
  }
  return <section className="section-card" id="tasks"><div className="section-heading"><h2>Tasks</h2><button className="button button-small" onClick={() => { setEditing(null); setOpen(!open); }}>Add task</button></div>{error && <Failure>{error}</Failure>}
    {!items.length ? <Empty>No tasks recorded.</Empty> : <div className="record-list">{items.map(item => <div className="record" key={item.id}><div className="record-head"><div><h3>{item.title}</h3><p>{item.description}</p><div className="record-meta"><StatusBadge value={item.status} /><span className="badge">{item.type}</span><span className="badge">{item.priority}</span>{item.blocking && <StatusBadge value="blocking" />}</div>{(item.related_requirement_id || item.related_document_id) && <p className="muted">Related: {requirements.find(requirement => requirement.id === item.related_requirement_id)?.document_type}{item.related_requirement_id && item.related_document_id ? " · " : ""}{documents.find(document => document.id === item.related_document_id)?.original_filename}</p>}</div><div className="button-row"><button className="button button-secondary button-small" onClick={() => { setEditing(item); setOpen(true); }}>Edit</button>{item.status !== "completed" && <button className="button button-small" onClick={() => void saveStatus(item, "completed")}>Complete</button>}{item.status !== "cancelled" && <button className="button button-danger button-small" onClick={() => void saveStatus(item, "cancelled")}>Cancel</button>}</div></div></div>)}</div>}
    {open && <form className="form-grid" onSubmit={submit} key={editing?.id ?? "new"}><div className="field"><label>Type</label><input name="type" required defaultValue={editing?.type ?? "manual_follow_up"} /></div><div className="field"><label>Title</label><input name="title" required defaultValue={editing?.title} /></div><div className="field field-full"><label>Description</label><textarea name="description" defaultValue={editing?.description} /></div><div className="field"><label>Status</label><select name="status" defaultValue={editing?.status ?? "open"}>{TASK_STATUSES.map(value => <option key={value}>{value}</option>)}</select></div><div className="field"><label>Priority</label><input name="priority" required defaultValue={editing?.priority ?? "normal"} /></div><div className="field"><label>Related requirement</label><select name="related_requirement_id" defaultValue={editing?.related_requirement_id ?? ""}><option value="">None</option>{requirements.map(item => <option key={item.id} value={item.id}>{item.document_type}</option>)}</select></div><div className="field"><label>Related document</label><select name="related_document_id" defaultValue={editing?.related_document_id ?? ""}><option value="">None</option>{documents.map(item => <option key={item.id} value={item.id}>{item.original_filename}</option>)}</select></div><fieldset className="field field-full"><div className="checkboxes"><label><input name="blocking" type="checkbox" defaultChecked={editing?.blocking ?? false} />Blocking</label></div></fieldset>{error && <Failure>{error}</Failure>}<div className="button-row field-full"><button className="button">Save task</button><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button></div></form>}
  </section>;
}
