import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, expect, it, vi } from "vitest";
import { api } from "@/lib/api";
import { DocumentsSection, FactsSection, PeopleSection, RequirementsSection, TasksSection } from "./CaseSections";
import { detail } from "@/test/fixtures";

vi.mock("@/lib/api", async () => { const actual = await vi.importActual<typeof import("@/lib/api")>("@/lib/api"); return { ...actual, api: Object.fromEntries(Object.entries(actual.api).map(([key, value]) => [key, /^(create|update|evaluate|upload|matching|match|unmatch|classify|accept|correct|reject|run)/.test(key) ? vi.fn() : value])) }; });

const suggestion = {
  id: "classification-1", document_id: "doc-1", suggested_document_type: "passport_bio_page", suggested_person_id: "person-1", extracted_owner_name: "Amina Diallo", confidence: 0.96,
  evidence_json: [{ type: "classification", value: "Passport header detected" }, { type: "text", value: "Owner name marker: Amina Diallo" }], provider: "synthetic_fake", model_version: "test-v1", document_hash: "a".repeat(64), raw_result_json: null,
  status: "suggested" as const, failure_reason: null, created_at: "2026-10-02T10:00:00Z", reviewed_at: null, reviewed_by: null, corrected_document_type: null, corrected_person_id: null,
};
const qualityCheck = {
  id: "quality-1", document_id: "doc-1", status: "manual_review" as const,
  checks_json: [{ check_id: "passport_bio_page_visible", status: "manual_review" as const, evidence: "PDF opens correctly", issue: "Employee confirmation required", evaluator: "manual_only", confidence: null }],
  issues_json: [{ check_id: "passport_bio_page_visible", message: "Employee confirmation required" }], extracted_metadata_json: {}, provider: "manual_only", evaluator_version: "profiles-v1", document_hash: "b".repeat(64), created_at: "2026-10-02T10:00:00Z", reviewed_at: null, reviewed_by: null, review_decision: null, review_reason: null,
};

beforeEach(() => vi.clearAllMocks());
it("supports manual person creation with multiple roles", async () => { vi.mocked(api.createPerson).mockResolvedValue(detail.people[0]); const changed = vi.fn(); const user = userEvent.setup(); render(<PeopleSection caseId="case-1" items={[]} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Add person" })); await user.type(screen.getByLabelText("First name"), "Amina"); await user.type(screen.getByLabelText("Last name"), "Diallo"); await user.click(screen.getByLabelText("sponsor")); await user.click(screen.getByRole("button", { name: "Save person" })); expect(api.createPerson).toHaveBeenCalledWith("case-1", { first_name: "Amina", last_name: "Diallo", roles: ["applicant", "sponsor"] }); });
it("displays and edits multiple person roles", async () => { vi.mocked(api.updatePerson).mockResolvedValue({ ...detail.people[0], roles: ["applicant", "sponsor"] }); const user = userEvent.setup(); render(<PeopleSection caseId="case-1" items={[{ ...detail.people[0], roles: ["applicant", "sponsor"] }]} onChanged={vi.fn()} />); expect(screen.getByText("applicant")).toBeInTheDocument(); expect(screen.getByText("sponsor")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Edit" })); await user.click(screen.getByRole("button", { name: "Save person" })); expect(api.updatePerson).toHaveBeenCalledWith("person-1", expect.objectContaining({ roles: ["applicant", "sponsor"] })); });
it("renders fact, requirement, document and task status", () => { const changed = vi.fn(); render(<><FactsSection caseId="case-1" items={detail.facts} people={detail.people} onChanged={changed} /><RequirementsSection caseId="case-1" items={detail.requirements} people={detail.people} documents={detail.documents} matches={detail.documentMatches} onChanged={changed} /><DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={detail.documentMatches} onChanged={changed} /><TasksSection caseId="case-1" items={detail.tasks} requirements={detail.requirements} documents={detail.documents} onChanged={changed} /></>); expect(screen.getByText("conflict")).toBeInTheDocument(); expect(screen.getAllByText("pending").length).toBeGreaterThan(0); expect(screen.getAllByText("passport.pdf").length).toBeGreaterThan(0); expect(screen.getByText("Review passport")).toBeInTheDocument(); });
it("completes a task through the task API", async () => { vi.mocked(api.updateTask).mockResolvedValue({ ...detail.tasks[0], status: "completed" }); const changed = vi.fn(); const user = userEvent.setup(); render(<TasksSection caseId="case-1" items={detail.tasks} requirements={detail.requirements} documents={detail.documents} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Complete" })); expect(api.updateTask).toHaveBeenCalledWith("task-1", expect.objectContaining({ status: "completed" })); });
it("edits a fact manually and keeps conflicts visually identifiable", async () => { vi.mocked(api.updateFact).mockResolvedValue(detail.facts[0]); const user = userEvent.setup(); const { container } = render(<FactsSection caseId="case-1" items={detail.facts} people={detail.people} onChanged={vi.fn()} />); expect(container.querySelector(".record-conflict")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Edit" })); await user.selectOptions(container.querySelector('select[name="status"]') as HTMLSelectElement, "confirmed"); await user.click(screen.getByRole("button", { name: "Save fact" })); expect(api.updateFact).toHaveBeenCalledWith("fact-1", expect.objectContaining({ status: "confirmed" })); });
it("distinguishes waived requirements", () => { const waived = { ...detail.requirements[0], id: "req-2", fulfillment_status: "waived" as const, fulfillment_source: "waived" as const, waiver_reason: "Not applicable", waived_by: "employee" }; render(<RequirementsSection caseId="case-1" items={[detail.requirements[0], waived]} people={detail.people} documents={detail.documents} matches={detail.documentMatches} onChanged={vi.fn()} />); expect(screen.getAllByText("waived").some(item => item.classList.contains("badge-waived"))).toBe(true); expect(screen.getByText(/Waived by employee/)).toBeInTheDocument(); });
it("distinguishes automatic and manual requirements and re-evaluates through the API", async () => { const automatic = { ...detail.requirements[0], id: "req-auto", rule_id: "TRV_SPONSOR_BANK_001" }; vi.mocked(api.evaluateRequirements).mockResolvedValue({ created: [], reactivated: [], deactivated: [], unchanged: [automatic] }); const changed = vi.fn(); const user = userEvent.setup(); render(<RequirementsSection caseId="case-1" items={[detail.requirements[0], automatic]} people={detail.people} documents={detail.documents} matches={detail.documentMatches} onChanged={changed} />); expect(screen.getByText("Manual")).toBeInTheDocument(); expect(screen.getByText("Automatic")).toBeInTheDocument(); expect(screen.getByText(/TRV_SPONSOR_BANK_001/)).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Re-evaluate rules" })); expect(api.evaluateRequirements).toHaveBeenCalledWith("case-1"); expect(await screen.findByRole("status")).toHaveTextContent("0 created, 0 reactivated, 0 deactivated"); });

it("uploads a selected file with optional assignment", async () => { const uploaded = detail.documents[0]; vi.mocked(api.uploadDocument).mockResolvedValue(uploaded); const user = userEvent.setup(); render(<DocumentsSection caseId="case-1" items={[]} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} onChanged={vi.fn().mockResolvedValue(undefined)} />); await user.click(screen.getByRole("button", { name: "Upload document" })); const file = new File(["%PDF-1.4 synthetic"], "synthetic.pdf", { type: "application/pdf" }); await user.upload(screen.getByLabelText("File"), file); await user.selectOptions(screen.getByLabelText("Document type (optional)"), "passport_bio_page"); await user.selectOptions(screen.getByLabelText("Person (optional)"), "person-1"); await user.click(screen.getByRole("button", { name: "Upload" })); expect(api.uploadDocument).toHaveBeenCalledWith("case-1", file, "passport_bio_page", "person-1"); expect(await screen.findByRole("status")).toHaveTextContent("synthetic.pdf uploaded"); });

it("assigns document type and person without exposing storage paths", async () => { vi.mocked(api.updateDocument).mockResolvedValue(detail.documents[0]); const user = userEvent.setup(); render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} onChanged={vi.fn().mockResolvedValue(undefined)} />); await user.click(screen.getByRole("button", { name: "Change metadata" })); await user.click(screen.getByRole("button", { name: "Save assignment" })); expect(api.updateDocument).toHaveBeenCalledWith("doc-1", { document_type: "passport_bio_page", person_id: "person-1" }); expect(screen.queryByLabelText(/storage/i)).not.toBeInTheDocument(); expect(screen.getByLabelText("Document quality")).toBeInTheDocument(); });

it("renders structured quality issues and runs an explicit quality check", async () => { vi.mocked(api.runQualityCheck).mockResolvedValue(qualityCheck); const user = userEvent.setup(); render(<DocumentsSection caseId="case-1" items={[{ ...detail.documents[0], quality_status: "manual_review" }]} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} qualityChecks={[qualityCheck]} onChanged={vi.fn().mockResolvedValue(undefined)} />); expect(screen.getAllByText(/Employee confirmation required/).length).toBeGreaterThan(0); await user.click(screen.getByRole("button", { name: "Run quality check again" })); expect(api.runQualityCheck).toHaveBeenCalledWith("doc-1"); });

it("requires a reason for explicit manual quality acceptance and rejection", async () => { vi.mocked(api.acceptQuality).mockResolvedValue({ ...qualityCheck, review_decision: "accepted" }); vi.mocked(api.rejectQuality).mockResolvedValue({ ...qualityCheck, review_decision: "rejected" }); const user = userEvent.setup(); const changed = vi.fn().mockResolvedValue(undefined); render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} qualityChecks={[qualityCheck]} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Accept document manually" })); await user.type(screen.getByLabelText("Reason"), "Original verified"); await user.click(screen.getAllByRole("button", { name: "Accept document manually" })[1]); expect(api.acceptQuality).toHaveBeenCalledWith("doc-1", "quality-1", "manual-ui", "Original verified"); });

it("separates matched, accepted and fulfilled requirement state", async () => { vi.mocked(api.evaluateCompleteness).mockResolvedValue({ id: "evaluation-1", requirement_id: "req-1", status: "incomplete", matched_document_ids_json: ["doc-1"], accepted_document_ids_json: [], matched_count: 1, accepted_count: 0, coverage_json: {}, missing_json: ["accepted_document"], explanation: "No accepted evidence", trigger: "explicit", created_at: "2026-10-02T10:00:00Z" }); const user = userEvent.setup(); render(<RequirementsSection caseId="case-1" items={detail.requirements} people={detail.people} documents={detail.documents} matches={detail.documentMatches} onChanged={vi.fn().mockResolvedValue(undefined)} />); expect(screen.getByText("Matched documents:").parentElement).toHaveTextContent("1"); expect(screen.getByText("Accepted documents:").parentElement).toHaveTextContent("0"); expect(screen.getByText("Requirement status:").parentElement).toHaveTextContent("pending"); await user.click(screen.getByRole("button", { name: "Evaluate completeness" })); expect(api.evaluateCompleteness).toHaveBeenCalledWith("req-1"); });

it("creates and removes manual matches", async () => { vi.mocked(api.matchingRequirements).mockResolvedValue(detail.requirements); vi.mocked(api.matchDocument).mockResolvedValue(detail.documentMatches[0]); vi.mocked(api.unmatchDocument).mockResolvedValue(undefined); const user = userEvent.setup(); const changed = vi.fn().mockResolvedValue(undefined); const { rerender } = render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Manage matches" })); await user.click(await screen.findByRole("button", { name: "Match" })); expect(api.matchDocument).toHaveBeenCalledWith("req-1", "doc-1", "manual-ui"); rerender(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={detail.documentMatches} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Manage matches" })); await user.click(screen.getByRole("button", { name: "Unmatch" })); expect(api.unmatchDocument).toHaveBeenCalledWith("req-1", "doc-1"); });

it("shows matched documents without implying quality approval", () => { render(<RequirementsSection caseId="case-1" items={detail.requirements} people={detail.people} documents={detail.documents} matches={detail.documentMatches} onChanged={vi.fn()} />); expect(screen.getByText("Matched documents")).toBeInTheDocument(); expect(screen.getByText("Matched only — not quality-approved.")).toBeInTheDocument(); expect(screen.getByRole("link", { name: "passport.pdf" })).toHaveAttribute("href", expect.stringContaining("/documents/doc-1/content")); });

it("shows automatic suggestion, confidence, owner and concise evidence", () => { render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} classifications={[suggestion]} onChanged={vi.fn()} />); expect(screen.getByText("Automatic suggestion")).toBeInTheDocument(); expect(screen.getByText("96%")).toBeInTheDocument(); expect(screen.getAllByText("Amina Diallo").length).toBeGreaterThan(0); expect(screen.getByText("Passport header detected")).toBeInTheDocument(); expect(screen.getByText(/Suggestions are not authoritative/)).toBeInTheDocument(); });

it("explicitly classifies and accepts a suggestion", async () => { vi.mocked(api.classifyDocument).mockResolvedValue(suggestion); vi.mocked(api.acceptClassification).mockResolvedValue({ ...suggestion, status: "accepted", reviewed_by: "manual-ui" }); const changed = vi.fn().mockResolvedValue(undefined); const user = userEvent.setup(); const { rerender } = render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} classifications={[]} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Classify document" })); expect(api.classifyDocument).toHaveBeenCalledWith("doc-1"); rerender(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} classifications={[suggestion]} onChanged={changed} />); await user.click(screen.getByRole("button", { name: "Accept suggestion" })); expect(api.acceptClassification).toHaveBeenCalledWith("doc-1", "classification-1", "manual-ui"); });

it("corrects a suggestion using catalog and case people", async () => { vi.mocked(api.correctClassification).mockResolvedValue({ ...suggestion, status: "corrected", corrected_document_type: "bank_statements", corrected_person_id: "person-1" }); const user = userEvent.setup(); render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} classifications={[suggestion]} onChanged={vi.fn().mockResolvedValue(undefined)} />); await user.click(screen.getByRole("button", { name: "Correct suggestion" })); await user.selectOptions(screen.getByLabelText("Correct document type"), "bank_statements"); await user.click(screen.getByRole("button", { name: "Save correction" })); expect(api.correctClassification).toHaveBeenCalledWith("doc-1", "classification-1", { reviewed_by: "manual-ui", document_type: "bank_statements", person_id: "person-1" }); });

it("rejects a suggestion without hiding manual fallback", async () => { vi.mocked(api.rejectClassification).mockResolvedValue({ ...suggestion, status: "rejected", reviewed_by: "manual-ui" }); const user = userEvent.setup(); render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} classifications={[suggestion]} onChanged={vi.fn().mockResolvedValue(undefined)} />); await user.click(screen.getByRole("button", { name: "Reject suggestion" })); expect(api.rejectClassification).toHaveBeenCalledWith("doc-1", "classification-1", "manual-ui"); expect(screen.getByRole("button", { name: "Change metadata" })).toBeInTheDocument(); });

it("shows controlled failure with retry and manual assignment", () => { const failed = { ...suggestion, id: "classification-failed", status: "failed" as const, failure_reason: "Classification provider is not configured or supported." }; render(<DocumentsSection caseId="case-1" items={detail.documents} people={detail.people} requirements={detail.requirements} documentTypes={detail.documentTypes} matches={[]} classifications={[failed]} onChanged={vi.fn()} />); expect(screen.getByText(/Classification unavailable/)).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Try again" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Change metadata" })).toBeInTheDocument(); });
