import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, expect, it, vi } from "vitest";
import { api, type ConversationImport, type FactExtractionCandidate } from "@/lib/api";
import { detail } from "@/test/fixtures";
import { CommunicationsSection } from "./CommunicationsSection";

vi.mock("@/lib/api", async () => {
  const actual = await vi.importActual<typeof import("@/lib/api")>("@/lib/api");
  return { ...actual, api: { ...actual.api, pasteConversation: vi.fn(), uploadConversation: vi.fn(), extractConversationFacts: vi.fn(), acceptFactCandidate: vi.fn(), correctFactCandidate: vi.fn(), rejectFactCandidate: vi.fn() } };
});

const conversation: ConversationImport = { id: "conversation-1", case_id: "case-1", source_type: "whatsapp_paste", original_filename: null, imported_by: "employee", content_hash: "a".repeat(64), parse_status: "parsed_with_warnings", parse_warnings_json: [{ line: 3, message: "Line did not match" }], message_count: 2, imported_at: "2026-10-02T10:00:00Z" };
const factCandidate: FactExtractionCandidate = { id: "candidate-1", case_id: "case-1", conversation_import_id: "conversation-1", extraction_run_id: "run-1", key: "trip.payer", value_json: "sponsor", confidence: .97, evidence: "My father will pay", source_message_ids_json: ["message-1"], provider: "synthetic", model_version: "test", status: "conflict", conflicting_fact_id: "fact-1", authoritative_fact_id: null, corrected_value_json: null, created_at: "2026-10-02T10:01:00Z", reviewed_at: null, reviewed_by: null, review_reason: null };
const messages = [{ id: "message-1", conversation_import_id: "conversation-1", case_id: "case-1", sequence_number: 1, sender: "Synthetic Client", message_timestamp: "2026-10-02T09:00:00Z", text: "My father will pay", source_reference: "conversation:1;message:1", created_at: "2026-10-02T10:00:00Z" }];
const base = { caseId: "case-1", conversations: [conversation], messages, runs: [], candidates: [factCandidate], facts: detail.facts, onChanged: vi.fn().mockResolvedValue(undefined) };

beforeEach(() => vi.clearAllMocks());

it("imports pasted conversation text", async () => { vi.mocked(api.pasteConversation).mockResolvedValue(conversation); const user = userEvent.setup(); render(<CommunicationsSection {...base} conversations={[]} candidates={[]} messages={[]} />); await user.click(screen.getByRole("button", { name: "Paste conversation" })); await user.type(screen.getByLabelText("Conversation text"), "Synthetic chat"); await user.click(screen.getByRole("button", { name: "Import pasted conversation" })); expect(api.pasteConversation).toHaveBeenCalledWith("case-1", "Synthetic chat", "manual-ui"); });

it("imports a selected text export", async () => { vi.mocked(api.uploadConversation).mockResolvedValue({ ...conversation, source_type: "whatsapp_export", original_filename: "synthetic.txt" }); const user = userEvent.setup(); render(<CommunicationsSection {...base} conversations={[]} candidates={[]} messages={[]} />); const file = new File(["Synthetic"], "synthetic.txt", { type: "text/plain" }); await user.upload(screen.getByLabelText("Import WhatsApp .txt"), file); await user.click(screen.getByRole("button", { name: "Import selected .txt" })); expect(api.uploadConversation).toHaveBeenCalledWith("case-1", file, "manual-ui"); });

it("shows parser diagnostics and explicitly requests extraction", async () => { vi.mocked(api.extractConversationFacts).mockResolvedValue({ id: "run-1", conversation_import_id: "conversation-1", status: "completed", provider: "synthetic", model_version: "test", candidate_count: 1, rejected_output_count: 0, failure_reason: null, created_at: "2026-10-02T10:01:00Z", completed_at: "2026-10-02T10:01:01Z" }); const user = userEvent.setup(); render(<CommunicationsSection {...base} />); expect(screen.getByText("Parser warnings (1)")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Extract facts" })); expect(api.extractConversationFacts).toHaveBeenCalledWith("conversation-1"); });

it("renders conflict, current and suggested values, evidence and exact source", () => { render(<CommunicationsSection {...base} />); expect(screen.getByText("trip.payer — conflict")).toBeInTheDocument(); expect(screen.getByText(/Current confirmed value:/).parentElement).toHaveTextContent("P123"); expect(screen.getByText(/WhatsApp suggestion:/).parentElement).toHaveTextContent("sponsor"); expect(screen.getByText("My father will pay")).toBeInTheDocument(); expect(screen.getByText(/Import: pasted conversation/)).toBeInTheDocument(); expect(screen.getByText(/Synthetic Client/)).toBeInTheDocument(); });

it("supports accept, correction and keep-current decisions with reasons", async () => { vi.mocked(api.acceptFactCandidate).mockResolvedValue({ ...factCandidate, status: "accepted" }); vi.mocked(api.correctFactCandidate).mockResolvedValue({ ...factCandidate, status: "corrected" }); vi.mocked(api.rejectFactCandidate).mockResolvedValue({ ...factCandidate, status: "rejected" }); const user = userEvent.setup(); const { rerender } = render(<CommunicationsSection {...base} />); await user.click(screen.getByRole("button", { name: "Use WhatsApp value" })); await user.type(screen.getByLabelText("Reason"), "Client confirmed correction"); await user.click(screen.getByRole("button", { name: "Save decision" })); expect(api.acceptFactCandidate).toHaveBeenCalledWith("candidate-1", "manual-ui", "Client confirmed correction"); rerender(<CommunicationsSection {...base} />); await user.click(screen.getByRole("button", { name: "Correct" })); await user.clear(screen.getByLabelText("Correct value")); await user.type(screen.getByLabelText("Correct value"), "applicant"); await user.type(screen.getByLabelText("Reason"), "Employee clarified payer"); await user.click(screen.getByRole("button", { name: "Save decision" })); expect(api.correctFactCandidate).toHaveBeenCalledWith("candidate-1", "manual-ui", "Employee clarified payer", "applicant"); rerender(<CommunicationsSection {...base} />); await user.click(screen.getByRole("button", { name: "Keep current value" })); await user.type(screen.getByLabelText("Reason"), "Current form remains correct"); await user.click(screen.getByRole("button", { name: "Save decision" })); expect(api.rejectFactCandidate).toHaveBeenCalledWith("candidate-1", "manual-ui", "Current form remains correct"); });
