"""Exact header aliases verified against both anonymized CSV schemas."""

SCHEMA = {'relationships': {'marriage_start_date': ['Data em que seu casamento/união estável começou'],
                   'spouse_family_name': ['Sobrenome do cônjuge '],
                   'spouse_given_names': ['Nome do cônjuge'],
                   'spouse_date_of_birth': ['Data de nascimento do cônjuge'],
                   'spouse_occupation': ['Ocupação atual do cônjuge'],
                   'has_previous_relationship': ['Você já foi casado ou esteve em união estável '
                                                 'anteriormente?'],
                   'former_spouse_full_name': ['Nome completo do ex-cônjuge'],
                   'former_spouse_date_of_birth': ['Data de nascimento do ex-cônjuge'],
                   'previous_relationship_type': ['Qual foi o tipo de relacionamento?'],
                   'previous_start_date': ['Data de início do antigo relacionamento'],
                   'previous_end_date': ['Data de término do antigo relacionamento'],
                   'former_spouse_birth_city': ['Cidade de nascimento do ex-cônjuge'],
                   'former_spouse_occupation': ['Ocupação atual do ex-cônjuge'],
                   'former_spouse_address': ['Endereço atual do ex-cônjuge'],
                   'spouse_residence_answer': ['Seu cônjuge reside com você? Se não, informe o '
                                               'endereço em "outro".',
                                               'Seu cônjuge reside com você? Se não, informe o '
                                               'endereço em "outro".']},
 'parents': [{'full_name': ['Nome completo do genitor 1',
                            'Nome completo do responsável legal/genitor(a) 1.'],
              'date_of_birth': ['Data de nascimento do genitor 1',
                                'Data de nascimento do responsável legal/genitor(a) 1'],
              'birth_place': ['Cidade de nascimento do genitor 1',
                              'Cidade de nascimento do responsável legal/genitor(a) 1.'],
              'marital_status': ['Estado civil do genitor 1',
                                 'Estado civil do  do responsável legal/genitor(a) 1.'],
              'occupation': ['Ocupação atual do genitor 1',
                             'Ocupação atual do  responsável legal/genitor(a) 1.'],
              'address': ['Endereço completo atual do genitor 1',
                          'Endereço completo atual do responsável legal/genitor(a) 1.'],
              'death_details': ['Se seu genitor 1 for falecido, informar a data e a cidade do '
                                'óbito',
                                'Se seu responsável legal/genitor(a) for FALECIDO, informar a '
                                'data, cidade e estado do óbito.'],
              'accompanying_answer': ['Seu genitor 1 acompanhará você ao Canadá?',
                                      'Seu responsável legal/genitor(a) 1, acompanhará você ao '
                                      'Canadá?']},
             {'full_name': ['Nome completo do genitor 2',
                            'Nome completo do responsável legal/genitor(a) 2.'],
              'date_of_birth': ['Data de nascimento do genitor 2',
                                'Data de nascimento da responsável legal/genitor(a) 2.'],
              'birth_place': ['Cidade de nascimento do genitor 2',
                              'Cidade de nascimento do responsável legal/genitor(a) 2.'],
              'marital_status': ['Estado civil do genitor 2',
                                 'Estado civil do  do responsável legal/genitor(a) 2.'],
              'occupation': ['Ocupação atual do genitor 2',
                             'Ocupação atual do responsável legal/genitor(a) 2.'],
              'address': ['Endereço completo do genitor 2',
                          'Endereço completo do responsável legal/genitor(a) 2.'],
              'death_details': ['Se seu genitor for falecido, informar a data e a cidade do óbito',
                                'Se seu responsável legal/genitor(a) for FALECIDO, informar a '
                                'data, cidade e estado do óbito.'],
              'accompanying_answer': ['Seu genitor 2 acompanhará você ao Canadá?',
                                      'Seu responsável legal/genitor(a) 2. Acompanhará você ao '
                                      'Canadá?']}],
 'children': {'relationship': ['Tipo de filiação', 'Tipo de Filiação'],
              'full_name': ['Nome completo do filho', 'Nome completo do filho(a).'],
              'date_of_birth': ['Data de nascimento do filho', 'Data de nascimento do filho(a).'],
              'marital_status': ['Estado civil do filho', 'Estado civil do seu filho(a)'],
              'birth_place': ['Cidade e estado de nascimento do filho',
                              'Cidade e estado de nascimento do filho(a).'],
              'occupation': ['Ocupação atual do filho', 'Ocupação atual do filho(a).'],
              'address': ['Endereço completo do filho', 'Endereço completo do filho(a).'],
              'accompanying_answer': ['Seu filho acompanhará você ao Canadá?',
                                      'Seu filho(a) acompanhará você ao Canadá?']}}
